{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.130.754.0 (24.06)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Territory Lookup\",\"Product Categories Lookup\",\"Largest AssetManagment Firms\",\"Customer Lookup\",\"Rolling Calendar\",\"Calendar Lookup\",\"Product Subcategories Lookup\",\"Product Category Sales (Unpivot Demo)\",\"Returns Data\",\"Parameter1\",\"Transform Sample File\",\"Sample File\",\"Transform File\",\"Measure Table\",\"Sales Data\",\"Parameter2\",\"Transform Sample File (2)\",\"Sample File (2)\",\"Transform File (2)\",\"Product Lookup\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-ZA",
    "cultures": [
      {
        "name": "en-ZA",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Largest AssetManagment Firms",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Web.BrowserContents(\"https://en.wikipedia.org/wiki/list_of_asset_management_firms\"),",
          "    #\"Extracted Table From Html\" = Html.Table(Source, {{\"Column1\", \"TABLE.sortable.wikitable > * > TR > :nth-child(1)\"}, {\"Column2\", \"TABLE.sortable.wikitable > * > TR > :nth-child(2)\"}, {\"Column3\", \"TABLE.sortable.wikitable > * > TR > :nth-child(3)\"}, {\"Column4\", \"TABLE.sortable.wikitable > * > TR > :nth-child(4)\"}}, [RowSelector=\"TABLE.sortable.wikitable > * > TR\"]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Extracted Table From Html\", [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Rank\", Int64.Type}, {\"Firm/company\", type text}, {\"Country\", type text}, {\"AUM (billion USD)\", type number}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "41b60037-4ede-4372-92ec-0b56a47af876"
      },
      {
        "name": "Rolling Calendar",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "List"
          }
        ],
        "expression": [
          "let",
          "    Source = #date(2023,1,1),",
          "    Custom1 = List.Dates(Source,Number.From(DateTime.LocalNow()) - Number.From(Source),#duration(1,0,0,0))",
          "in",
          "    Custom1"
        ],
        "kind": "m",
        "lineageTag": "ecb3b5d1-099d-43a7-b806-2b96725c8253"
      },
      {
        "name": "Product Category Sales (Unpivot Demo)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(\"C:\\Users\\Rivashan Govender\\Downloads\\AdventureWorks+Raw+Data\\AdventureWorks Raw Data\\Product Category Sales (Unpivot Demo).csv\"),[Delimiter=\",\", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Date\", type date}, {\"Product Category\", type text}, {\"North Region\", Int64.Type}, {\"Central Region\", Int64.Type}, {\"South Region\", Int64.Type}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "f94b3b8f-0cea-4a8b-82fc-264a1790e7a8"
      },
      {
        "name": "Parameter1",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": "#\"Sample File\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Sample File\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "6dfe4829-225d-45d7-b107-d5eaff78e41b",
        "queryGroup": "Transform File from Sales Data\\Helper Queries"
      },
      {
        "name": "Transform Sample File",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(Parameter1,[Delimiter=\",\", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])",
          "in",
          "    #\"Promoted Headers\""
        ],
        "kind": "m",
        "lineageTag": "0adbc739-60ac-429e-83a8-76528c6fe9c9",
        "queryGroup": "Transform File from Sales Data"
      },
      {
        "name": "Sample File",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let",
          "    Source = Folder.Files(\"C:\\Users\\Rivashan Govender\\Downloads\\AdventureWorks+Raw+Data\\AdventureWorks Raw Data\\Sales Data\"),",
          "    #\"C:\\Users\\Rivashan Govender\\Downloads\\AdventureWorks+Raw+Data\\AdventureWorks Raw Data\\Sales Data\\_AdventureWorks Sales Data 2021 csv\" = Source{[#\"Folder Path\"=\"C:\\Users\\Rivashan Govender\\Downloads\\AdventureWorks+Raw+Data\\AdventureWorks Raw Data\\Sales Data\\\",Name=\"AdventureWorks Sales Data 2021.csv\"]}[Content]",
          "in",
          "    #\"C:\\Users\\Rivashan Govender\\Downloads\\AdventureWorks+Raw+Data\\AdventureWorks Raw Data\\Sales Data\\_AdventureWorks Sales Data 2021 csv\""
        ],
        "kind": "m",
        "lineageTag": "e2cf6b55-beac-47ea-8ae0-675aeffc9219",
        "queryGroup": "Transform File from Sales Data\\Helper Queries"
      },
      {
        "name": "Transform File",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = (Parameter1 as binary) => let",
          "    Source = Csv.Document(Parameter1,[Delimiter=\",\", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])",
          "in",
          "    #\"Promoted Headers\"",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "c5b88f45-aa5c-46b2-bab5-a0ad2df4dd46",
        "mAttributes": "[ FunctionQueryBinding = \"{\"\"exemplarFormulaName\"\":\"\"Transform Sample File\"\"}\" ]",
        "queryGroup": "Transform File from Sales Data\\Helper Queries"
      },
      {
        "name": "Parameter2",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": "#\"Sample File (2)\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Sample File (2)\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "32dcdff9-d9e3-4cdf-9a0e-6dc7ca81711c",
        "queryGroup": "Transform File from Sales Data (2)\\Helper Queries"
      },
      {
        "name": "Transform Sample File (2)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(Parameter2,[Delimiter=\",\", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])",
          "in",
          "    #\"Promoted Headers\""
        ],
        "kind": "m",
        "lineageTag": "3efc7688-0957-4353-92cd-1286e3fdf623",
        "queryGroup": "Transform File from Sales Data (2)"
      },
      {
        "name": "Sample File (2)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let",
          "    Source = Folder.Files(\"C:\\Users\\Rivashan Govender\\Downloads\\AdventureWorks+Raw+Data\\AdventureWorks Raw Data\\Sales Data\"),",
          "    #\"C:\\Users\\Rivashan Govender\\Downloads\\AdventureWorks+Raw+Data\\AdventureWorks Raw Data\\Sales Data\\_AdventureWorks Sales Data 2021 csv\" = Source{[#\"Folder Path\"=\"C:\\Users\\Rivashan Govender\\Downloads\\AdventureWorks+Raw+Data\\AdventureWorks Raw Data\\Sales Data\\\",Name=\"AdventureWorks Sales Data 2021.csv\"]}[Content]",
          "in",
          "    #\"C:\\Users\\Rivashan Govender\\Downloads\\AdventureWorks+Raw+Data\\AdventureWorks Raw Data\\Sales Data\\_AdventureWorks Sales Data 2021 csv\""
        ],
        "kind": "m",
        "lineageTag": "da3d24b2-3cda-4c35-85f1-dfc7120eabf1",
        "queryGroup": "Transform File from Sales Data (2)\\Helper Queries"
      },
      {
        "name": "Transform File (2)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = (Parameter2 as binary) => let",
          "    Source = Csv.Document(Parameter2,[Delimiter=\",\", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])",
          "in",
          "    #\"Promoted Headers\"",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "eab5c9f1-970a-4c48-8b56-6757e0bd3aea",
        "mAttributes": "[ FunctionQueryBinding = \"{\"\"exemplarFormulaName\"\":\"\"Transform Sample File (2)\"\"}\" ]",
        "queryGroup": "Transform File from Sales Data (2)\\Helper Queries"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "OtherQueries"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Transform File from Sales Data"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transform File from Sales Data\\Helper Queries"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "3"
          }
        ],
        "folder": "Transform File from Sales Data (2)"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transform File from Sales Data (2)\\Helper Queries"
      }
    ],
    "relationships": [
      {
        "name": "923c041a-ea14-be2e-e173-6aba4df0a577",
        "fromColumn": "TerritoryKey",
        "fromTable": "Sales Data",
        "toColumn": "SalesTerritoryKey",
        "toTable": "Territory Lookup"
      },
      {
        "name": "f9d96f35-077b-8633-4cf8-552412aeffea",
        "fromColumn": "OrderDate",
        "fromTable": "Sales Data",
        "toColumn": "Date",
        "toTable": "Calendar Lookup"
      },
      {
        "name": "f6c7bf41-0348-ec57-5615-be3944e57244",
        "fromColumn": "CustomerKey",
        "fromTable": "Sales Data",
        "toColumn": "CustomerKey",
        "toTable": "Customer Lookup"
      },
      {
        "name": "8e628d5f-ac4b-a382-d94d-a29e72fafd1f",
        "fromColumn": "ProductCategoryKey",
        "fromTable": "Product Subcategories Lookup",
        "toColumn": "ProductCategoryKey",
        "toTable": "Product Categories Lookup"
      },
      {
        "name": "e4daccf9-96dc-7ac1-f561-d8cd387e0732",
        "fromColumn": "ReturnDate",
        "fromTable": "Returns Data",
        "toColumn": "Date",
        "toTable": "Calendar Lookup"
      },
      {
        "name": "74a7052f-b9fb-0797-6d9b-ee8712b28088",
        "fromColumn": "TerritoryKey",
        "fromTable": "Returns Data",
        "toColumn": "SalesTerritoryKey",
        "toTable": "Territory Lookup"
      },
      {
        "name": "ba02dac5-f246-ce7e-9975-029e60553eeb",
        "fromColumn": "ProductSubcategoryKey",
        "fromTable": "Product Lookup",
        "toColumn": "ProductSubcategoryKey",
        "toTable": "Product Subcategories Lookup"
      },
      {
        "name": "15f569f6-f6cd-bb49-8c3c-8721faa696f3",
        "fromColumn": "ProductKey",
        "fromTable": "Returns Data",
        "toColumn": "ProductKey",
        "toTable": "Product Lookup"
      },
      {
        "name": "bd13fb7e-2b76-a16b-53fc-03f3f9bd19e1",
        "fromColumn": "ProductKey",
        "fromTable": "Sales Data",
        "toColumn": "ProductKey",
        "toTable": "Product Lookup"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Territory Lookup",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "SalesTerritoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b3223d23-99e0-4378-bd80-67a3a6bccb7c",
            "sourceColumn": "SalesTerritoryKey",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f1706bd1-f427-4961-8990-3542a7071ae9",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b14aaf4e-00b9-4e7d-ae56-910a4af34353",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Continent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cc68bf49-503e-425d-a502-58951bd9115d",
            "sourceColumn": "Continent",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f08d175e-61d1-4d59-a9c8-63aa40791501",
        "partitions": [
          {
            "name": "Territory Lookup",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\Rivashan Govender\\Downloads\\AdventureWorks+Raw+Data\\AdventureWorks Raw Data\\AdventureWorks Territory Lookup.csv\"),[Delimiter=\",\", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"SalesTerritoryKey\", Int64.Type}, {\"Region\", type text}, {\"Country\", type text}, {\"Continent\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Product Categories Lookup",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ProductCategoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e8d4e841-63ca-4d0d-86d9-570c9ad7287c",
            "sourceColumn": "ProductCategoryKey",
            "summarizeBy": "none"
          },
          {
            "name": "CategoryName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "69e3eb89-ac57-44e5-be40-520ca1827913",
            "sourceColumn": "CategoryName",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7b90bb25-f275-4419-92c2-9bd1e9a98a18",
        "partitions": [
          {
            "name": "Product Categories Lookup",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\Rivashan Govender\\Downloads\\AdventureWorks+Raw+Data\\AdventureWorks Raw Data\\AdventureWorks Product Categories Lookup.csv\"),[Delimiter=\",\", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ProductCategoryKey\", Int64.Type}, {\"CategoryName\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Product Subcategories Lookup",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ProductSubcategoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b09e2f2b-8071-4dcc-8bbf-2a2287008d40",
            "sourceColumn": "ProductSubcategoryKey",
            "summarizeBy": "none"
          },
          {
            "name": "SubcategoryName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ff2ad579-68ac-4bc9-b57d-cb56c98cd9b6",
            "sourceColumn": "SubcategoryName",
            "summarizeBy": "none"
          },
          {
            "name": "ProductCategoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e03153a7-4129-4cfe-999c-91257ae2601f",
            "sourceColumn": "ProductCategoryKey",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7d5e9b31-ecb2-40a6-b6ab-321ee94c8601",
        "partitions": [
          {
            "name": "Product Subcategories Lookup",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\Rivashan Govender\\Downloads\\AdventureWorks+Raw+Data\\AdventureWorks Raw Data\\AdventureWorks Product Subcategories Lookup.csv\"),[Delimiter=\",\", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ProductSubcategoryKey\", Int64.Type}, {\"SubcategoryName\", type text}, {\"ProductCategoryKey\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Customer Lookup",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CustomerKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "759816b1-84a3-467a-88c6-a761e351cead",
            "sourceColumn": "CustomerKey",
            "summarizeBy": "none"
          },
          {
            "name": "Prefix",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7cca9fd9-72cc-4289-91ca-64e0293ad0a3",
            "sourceColumn": "Prefix",
            "summarizeBy": "none"
          },
          {
            "name": "FirstName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9f81d6bf-bddd-420f-a372-854c06ae06d9",
            "sourceColumn": "FirstName",
            "summarizeBy": "none"
          },
          {
            "name": "LastName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1d066a86-499a-4dd5-a7c8-fa30d8c1ac57",
            "sourceColumn": "LastName",
            "summarizeBy": "none"
          },
          {
            "name": "BirthDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "1b633fbd-5843-46af-9778-5c1760d8e78b",
            "sourceColumn": "BirthDate",
            "summarizeBy": "none"
          },
          {
            "name": "MaritalStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a11ef086-b23f-4ff8-b61e-b5eb2a7edc71",
            "sourceColumn": "MaritalStatus",
            "summarizeBy": "none"
          },
          {
            "name": "Gender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "07b30236-ba39-4bc3-881c-a9ef3665f85a",
            "sourceColumn": "Gender",
            "summarizeBy": "none"
          },
          {
            "name": "EmailAddress",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0381e882-be49-4bd2-9a0c-457c0e825b46",
            "sourceColumn": "EmailAddress",
            "summarizeBy": "none"
          },
          {
            "name": "AnnualIncome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "42db2235-ffb0-4ea3-aab8-0689dba66dfb",
            "sourceColumn": "AnnualIncome",
            "summarizeBy": "none"
          },
          {
            "name": "TotalChildren",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6d17fada-7ada-4fc6-a220-b49502430124",
            "sourceColumn": "TotalChildren",
            "summarizeBy": "none"
          },
          {
            "name": "EducationLevel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f1db03cb-bf5f-41ef-bd7c-3b4dae1c8761",
            "sourceColumn": "EducationLevel",
            "summarizeBy": "none"
          },
          {
            "name": "Occupation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f66ecd5d-e3b0-4462-a914-206db95b09c4",
            "sourceColumn": "Occupation",
            "summarizeBy": "none"
          },
          {
            "name": "HomeOwner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f5402a67-5a44-4707-8f69-7e67b573e4e8",
            "sourceColumn": "HomeOwner",
            "summarizeBy": "none"
          },
          {
            "name": "Full Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a3f68017-10c0-4a45-a914-caa708715ffa",
            "sourceColumn": "Full Name",
            "summarizeBy": "none"
          },
          {
            "name": "Domain Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2fa5e76c-3725-4f08-a265-d88db8c2e55c",
            "sourceColumn": "Domain Name",
            "summarizeBy": "none"
          },
          {
            "name": "Parent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF(",
              "    'Customer Lookup'[TotalChildren] > 0,",
              "    \"Yes\",",
              "    \"No\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "d759908e-6942-40b1-a374-07a8859ec06b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Customer Priority",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF(",
              "    'Customer Lookup'[Parent]= \"Yes\" &&",
              "    'Customer Lookup'[AnnualIncome] > 100000,",
              "    \"Priority\",",
              "    \"Standard\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "f5e34c14-c281-4896-a2b3-f5ce11e36c94",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Income Level",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF('Customer Lookup' [AnnualIncome] >= 150000, \"Very High\",",
              "IF('Customer Lookup' [AnnualIncome] >= 100000, \"High\",",
              "IF('Customer Lookup' [AnnualIncome] >= 50000, \"Average\",",
              "\"Low\")))"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "6bdf0d09-f008-47ff-91e7-0fe16f64e2a4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Education Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "    'Customer Lookup' [EducationLevel],",
              "    \"High School\",\"High school\",",
              "    \"Partial High School\", \"High School\",",
              "    \"Bachelors\",\"Undergrad\",",
              "    \"Partial College\", \"Undergrad\",",
              "    \"Graduate Degree\", \"Graduate\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "020a1cd1-61b8-4bc5-98f6-9635ee54cbd5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Birth Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "YEAR(",
              "    'Customer Lookup'[BirthDate]",
              ")"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "74beff3a-49c5-4f29-ac77-c1605cf39ede",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "b1ccb86d-73cf-467e-8405-82f0d994d179",
        "partitions": [
          {
            "name": "Customer Lookup",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\Rivashan Govender\\Downloads\\AdventureWorks+Raw+Data\\AdventureWorks Raw Data\\AdventureWorks Customer Lookup.csv\"),[Delimiter=\",\", Columns=13, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"CustomerKey\", Int64.Type}, {\"Prefix\", type text}, {\"FirstName\", type text}, {\"LastName\", type text}, {\"BirthDate\", type date}, {\"MaritalStatus\", type text}, {\"Gender\", type text}, {\"EmailAddress\", type text}, {\"AnnualIncome\", Int64.Type}, {\"TotalChildren\", Int64.Type}, {\"EducationLevel\", type text}, {\"Occupation\", type text}, {\"HomeOwner\", type text}}),",
                "    #\"Removed Errors\" = Table.RemoveRowsWithErrors(#\"Changed Type\", {\"CustomerKey\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Errors\", each [CustomerKey] <> null and [CustomerKey] <> \"\"),",
                "    #\"Capitalized Each Word\" = Table.TransformColumns(#\"Filtered Rows\",{{\"Prefix\", Text.Proper, type text}, {\"FirstName\", Text.Proper, type text}, {\"LastName\", Text.Proper, type text}}),",
                "    #\"Inserted Full Name Column\" = Table.AddColumn(#\"Capitalized Each Word\", \"Full Name\", each Text.Combine({[Prefix], [FirstName], [LastName]}, \" \"), type text),",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Inserted Full Name Column\", \"EmailAddress\", \"EmailAddress - Copy\"),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Duplicated Column\",{{\"EmailAddress - Copy\", \"Domain Name\"}}),",
                "    #\"Extracted Text After Delimiter\" = Table.TransformColumns(#\"Renamed Columns\", {{\"Domain Name\", each Text.AfterDelimiter(_, \"@\"), type text}}),",
                "    #\"Extracted Text Before Delimiter\" = Table.TransformColumns(#\"Extracted Text After Delimiter\", {{\"Domain Name\", each Text.BeforeDelimiter(_, \".\"), type text}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Extracted Text Before Delimiter\",\"-\",\" \",Replacer.ReplaceText,{\"Domain Name\"}),",
                "    #\"Capitalized Each Word1\" = Table.TransformColumns(#\"Replaced Value\",{{\"Domain Name\", Text.Proper, type text}})",
                "in",
                "    #\"Capitalized Each Word1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Calendar Lookup",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "54a5fbd0-5ea8-4bf6-9b1d-4b9405ded555",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Day Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e855ba0b-2492-4669-959b-4c289808165b",
            "sourceColumn": "Day Name",
            "summarizeBy": "none"
          },
          {
            "name": "Start of Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "4608654d-3576-4512-a6f4-bfdb17b92bc2",
            "sourceColumn": "Start of Week",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "da1fa3fa-ad56-4684-b369-8ce082f709e7",
            "sourceColumn": "Month",
            "summarizeBy": "sum"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "31179101-49b9-4b0f-b315-9e0466d7da69",
            "sourceColumn": "Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "Start of Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "05e6337a-e520-44ea-9dd1-dffcfbd44e39",
            "sourceColumn": "Start of Month",
            "summarizeBy": "none"
          },
          {
            "name": "Start of Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "1ba70816-5859-4f91-81b6-bed7abf7d736",
            "sourceColumn": "Start of Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Start of Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "927c92b2-69c9-40ab-a4e7-3c03396dca8b",
            "sourceColumn": "Start of Year",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bc6b57a5-60e6-4d81-be78-d7ea20ec39bb",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Month Number (DAX)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "    'Calendar Lookup'[Month Name],",
              "    \"January\",\"1\",",
              "    \"February\",\"2\",",
              "    \"March\",\"3\",",
              "    \"April\",\"4\",",
              "    \"\",\"5\",",
              "    \"June\",\"6\",",
              "    \"July\" ,\"7\",",
              "    \"August\",\"8\",",
              "    \"September\",\"9\",",
              "    \"October\",\"10\",",
              "    \"November\",\"11\",",
              "    \"December\",\"12\",",
              "    \"Other\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "871a8083-602e-4dd3-a2c1-aa6277e2863d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month Short",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "UPPER(",
              "    LEFT(",
              "        'Calendar Lookup' [Month Name],",
              "        3",
              "    )",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "920a42cb-05eb-4645-b9c2-3b87a0b72436",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day of Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "WEEKDAY(",
              "    'Calendar Lookup'[Date],",
              "    2",
              ")"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "5c8e93b2-6957-47c9-8bb8-2aa8f1f73f8f",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Weekend",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF(",
              "    'Calendar Lookup' [Day of Week] = 6 ||",
              "    'Calendar Lookup' [Day of week] = 7,",
              "    \"Weekend\",",
              "    \"Weekday\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "38089cff-e9e7-4555-b392-49d1a4f31a5c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "c96f9f99-5856-492e-89a3-d818f5acf20d",
        "measures": [
          {
            "name": "Profit Target Gap",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Total Profit] -[Profit Target]",
            "lineageTag": "b3865467-d5e0-4ed4-94d9-ff99cf841957"
          },
          {
            "name": "Measure",
            "annotations": [
              {
                "name": "43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c",
                "value": "True"
              }
            ],
            "lineageTag": "5c0f4838-a538-4313-bc03-723ee867013d"
          }
        ],
        "partitions": [
          {
            "name": "Calendar Lookup",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\Rivashan Govender\\Downloads\\AdventureWorks+Raw+Data\\AdventureWorks Raw Data\\AdventureWorks Calendar Lookup.csv\"),[Delimiter=\",\", Columns=1, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Date\", type date}}),",
                "    #\"Inserted Day Name\" = Table.AddColumn(#\"Changed Type\", \"Day Name\", each Date.DayOfWeekName([Date]), type text),",
                "    #\"Inserted Start of Week\" = Table.AddColumn(#\"Inserted Day Name\", \"Start of Week\", each Date.StartOfWeek([Date]), type date),",
                "    #\"Changed Type with Locale\" = Table.TransformColumnTypes(#\"Inserted Start of Week\", {{\"Date\", type date}}, \"en-US\"),",
                "    #\"Changed Type with Locale1\" = Table.TransformColumnTypes(#\"Changed Type with Locale\", {{\"Start of Week\", type date}}, \"en-US\"),",
                "    #\"Inserted Year\" = Table.AddColumn(#\"Changed Type with Locale1\", \"Year\", each Date.Year([Date]), Int64.Type),",
                "    #\"Inserted Start of Quarter\" = Table.AddColumn(#\"Inserted Year\", \"Start of Quarter\", each Date.StartOfQuarter([Date]), type date),",
                "    #\"Inserted Start of Month\" = Table.AddColumn(#\"Inserted Start of Quarter\", \"Start of Month\", each Date.StartOfMonth([Date]), type date),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Inserted Start of Month\",{\"Date\", \"Day Name\", \"Start of Month\", \"Start of Week\", \"Year\", \"Start of Quarter\"}),",
                "    #\"Inserted Month\" = Table.AddColumn(#\"Reordered Columns\", \"Month\", each Date.Month([Start of Month]), Int64.Type),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Inserted Month\",{\"Date\", \"Day Name\", \"Month\", \"Start of Month\", \"Start of Week\", \"Year\", \"Start of Quarter\"}),",
                "    #\"Inserted Month Name\" = Table.AddColumn(#\"Reordered Columns1\", \"Month Name\", each Date.MonthName([Date]), type text),",
                "    #\"Reordered Columns2\" = Table.ReorderColumns(#\"Inserted Month Name\",{\"Date\", \"Day Name\", \"Month\", \"Month Name\", \"Start of Month\", \"Start of Quarter\", \"Start of Week\", \"Year\"}),",
                "    #\"Inserted Start of Year\" = Table.AddColumn(#\"Reordered Columns2\", \"Start of Year\", each Date.StartOfYear([Date]), type date),",
                "    #\"Reordered Columns3\" = Table.ReorderColumns(#\"Inserted Start of Year\",{\"Date\", \"Day Name\", \"Month\", \"Month Name\", \"Start of Month\", \"Start of Quarter\", \"Start of Week\", \"Start of Year\", \"Year\"})",
                "in",
                "    #\"Reordered Columns3\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Returns Data",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ReturnDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isHidden": true,
            "lineageTag": "4fe196ae-7472-42d6-8aba-291fac7fff20",
            "sourceColumn": "ReturnDate",
            "summarizeBy": "none"
          },
          {
            "name": "TerritoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "afe3fe1f-d49a-4fa5-96fe-ee9bc1a9d23b",
            "sourceColumn": "TerritoryKey",
            "summarizeBy": "none"
          },
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "6da48493-7c52-44d8-9896-4dce85bfc9fc",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "ReturnQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d008227a-16f3-4887-b669-6b2984a3e693",
            "sourceColumn": "ReturnQuantity",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "54f83496-3639-4d65-aa5d-f0aed75ea14d",
        "partitions": [
          {
            "name": "Returns Data",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\Rivashan Govender\\Downloads\\AdventureWorks+Raw+Data\\AdventureWorks Raw Data\\AdventureWorks Returns Data.csv\"),[Delimiter=\",\", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ReturnDate\", type date}, {\"TerritoryKey\", Int64.Type}, {\"ProductKey\", Int64.Type}, {\"ReturnQuantity\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Measure Table",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "00c7feb6-533f-4f6a-9eca-44c4d7b0ffaa",
        "measures": [
          {
            "name": "Order Quatity",
            "expression": [
              "",
              "SUM(",
              "    'Sales Data'[OrderQuantity]",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "c5b1d985-bcc1-4147-9a7e-e2dc0c9c9343"
          },
          {
            "name": "Quantity Returned",
            "expression": [
              "",
              "SUM(",
              "",
              "    'Returns Data'[ReturnQuantity]",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "e9ec9c10-099f-4144-9e97-7695720824c5"
          },
          {
            "name": "Average Retails Price",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-ZA\"}"
              }
            ],
            "expression": [
              "",
              "AVERAGE(",
              "    'Product Lookup'[ProductPrice]",
              ")"
            ],
            "formatString": "\"R\"#,0.###############;-\"R\"#,0.###############;\"R\"#,0.###############",
            "lineageTag": "a6fe0631-1edb-454a-b054-e077118462a0"
          },
          {
            "name": "Total Returns",
            "expression": [
              "",
              "COUNT(",
              "    'Returns Data'[ReturnQuantity]",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "23695877-4eb1-45ed-8e72-1722e287cb07"
          },
          {
            "name": "Quantity Sold",
            "expression": [
              "",
              "SUM(",
              "    'Sales Data'[OrderQuantity]",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "664bd3e9-0ed5-4a7f-b16e-52ae32c11bb7"
          },
          {
            "name": "Total Orders",
            "expression": [
              "",
              "DISTINCTCOUNT(",
              "    'Sales Data'[OrderNumber]",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "d309594b-d546-4917-9792-46b5bdc45e7b"
          },
          {
            "name": "Total Customers",
            "expression": [
              "",
              "DISTINCTCOUNT(",
              "    'Sales Data'[CustomerKey]",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "03391a2e-d310-4fad-8402-1b6c81399520"
          },
          {
            "name": "Return Rate",
            "expression": [
              "",
              "DIVIDE(",
              "[Quantity Returned],",
              "[Quantity Sold],",
              "\"No Sales\"",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "07a5b385-1a11-4f5e-a08a-ac80996614e8"
          },
          {
            "name": "Bulk Orders",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Orders],",
              "    'Sales Data'[OrderQuantity] > 1",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "f474bdac-2e1f-493d-bca1-d081b0c7df16"
          },
          {
            "name": "Weekend Orders",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Orders],",
              "    'Calendar Lookup'[Weekend] = \"Weekend\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "2cbfc249-f978-404b-a4d6-f4e986e6e276"
          },
          {
            "name": "Bike Returns",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Returns],",
              "    'Product Categories Lookup'[CategoryName] = \"Bikes\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "ba4e981f-ebe9-47f6-a166-28d543efe96d"
          },
          {
            "name": "Bike Sales",
            "expression": [
              "",
              "CALCULATE(",
              "    [Quantity Sold],",
              "    'Product Categories Lookup'[CategoryName] = \"Bikes\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "6d817acc-8f96-4ba3-982b-a1c37fca559d"
          },
          {
            "name": "Bike Return Rate",
            "expression": [
              "",
              "CALCULATE(",
              "    [Return Rate],",
              "    'Product Categories Lookup' [CategoryName] = \"Bikes\"",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "c7d2c9da-b498-498e-b4d9-84227dd86c65"
          },
          {
            "name": "All Orders",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Orders],",
              "    ALL(",
              "        'Sales Data'",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "4ded3b98-0a67-4828-b06c-db78e942f356"
          },
          {
            "name": "% Of ALL Orders",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE(",
              "    [Total Orders],",
              "    [All Orders]",
              ")"
            ],
            "lineageTag": "b9576210-9ee3-48b6-b0b5-2b51f335aafd"
          },
          {
            "name": "Overall Avg Price",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-ZA\"}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    [Average Retails Price],",
              "    ALL(",
              "        'Product Lookup'",
              "    )",
              ")"
            ],
            "formatString": "\"R\"#,0.###############;-\"R\"#,0.###############;\"R\"#,0.###############",
            "lineageTag": "f869b8d5-82b5-430e-a480-d38d213d7bbf"
          },
          {
            "name": "All Returns",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Returns],",
              "    ALL(",
              "        'Returns Data'",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "0352eb51-33e8-4fd5-ae30-5165e7cbcdaa"
          },
          {
            "name": "% All Returns",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE(",
              "    [Total Returns],",
              "    [All Returns]",
              ")"
            ],
            "lineageTag": "dcf33e86-cbbe-4465-9b2b-6c656c9bbcbd"
          },
          {
            "name": "High Ticket Orders",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Orders],",
              "    FILTER(",
              "        'Product Lookup',",
              "        'Product Lookup'[ProductPrice] > [Overall Avg Price]",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "e27bc331-1202-471e-8630-0a81b8455eaa"
          },
          {
            "name": "Total Revenue(CC)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-ZA\"}"
              }
            ],
            "expression": [
              "",
              "SUM(",
              "    'Sales Data'[Revenue]",
              ")"
            ],
            "formatString": "\"R\"#,0.###############;-\"R\"#,0.###############;\"R\"#,0.###############",
            "lineageTag": "4cad130f-3b8c-4dbd-aa81-0107bbe947b1"
          },
          {
            "name": "Total Revenue",
            "expression": [
              "",
              "SUMX(",
              "    'Sales Data',",
              "    'Sales Data'[OrderQuantity]*",
              "    RELATED(",
              "        'Product Lookup'[ProductPrice]",
              "    )",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "aeace4bf-932c-455c-bea7-32cf567387b2"
          },
          {
            "name": "Total Cost",
            "expression": [
              "",
              "SUMX (",
              "    'Sales Data',",
              "    'Sales Data'[OrderQuantity] *",
              "    RELATED(",
              "        'Product Lookup'[ProductCost]",
              "    )",
              ") "
            ],
            "formatString": "0.00",
            "lineageTag": "dd6f57b5-0d55-4469-9c5e-21f779752015"
          },
          {
            "name": "Total Profit",
            "expression": [
              "",
              "[Total Revenue] - [Total Cost]",
              ""
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "9e371bcd-ccb6-477a-b1a2-a72c9f0f338e"
          },
          {
            "name": "YTD Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-ZA\"}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "   [Total Revenue],",
              "    DATESYTD(",
              "        'Calendar Lookup'[Date]",
              "    )",
              ")"
            ],
            "formatString": "\"R\"#,0.###############;-\"R\"#,0.###############;\"R\"#,0.###############",
            "lineageTag": "9133d9e2-ebca-44d1-adc3-0663909a4f89"
          },
          {
            "name": "Previous Months Revenue",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Revenue],",
              "    DATEADD(",
              "        'Calendar Lookup'[Date],",
              "        -1,",
              "        MONTH",
              "    )",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "6bfb68cc-a96e-443a-8ede-3db948a79609"
          },
          {
            "name": "Revenue Target",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-ZA\"}"
              }
            ],
            "expression": [
              "",
              "[Previous Months Revenue] * 1.1"
            ],
            "formatString": "\"R\"#,0.###############;-\"R\"#,0.###############;\"R\"#,0.###############",
            "lineageTag": "d5006123-43bd-426b-93a0-52fd4ea86985"
          },
          {
            "name": "10-day Rolling Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-ZA\"}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Revenue],",
              "    DATESINPERIOD(",
              "        'Calendar Lookup'[Date],",
              "        MAX (",
              "            'Calendar Lookup'[Date]",
              "        ),",
              "        -10,",
              "        DAY",
              "    )",
              ")"
            ],
            "formatString": "\"R\"#,0.###############;-\"R\"#,0.###############;\"R\"#,0.###############",
            "lineageTag": "392c1c19-f67d-4b79-bfcf-38290fc2432a"
          },
          {
            "name": "Previous Month Returns",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Returns],",
              "    DATEADD(",
              "        'Calendar Lookup'[Date],",
              "        -1,",
              "        MONTH",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "1497e444-b43d-456e-a959-2a0ac13499d1"
          },
          {
            "name": "Previous Month Orders",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Orders],",
              "    DATEADD(",
              "        'Calendar Lookup'[Date],",
              "        -1,",
              "        MONTH",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "015f1e7a-bd8d-4378-ae0e-f883187a783a"
          },
          {
            "name": "Order Target",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "[Previous Month Orders] * 1.1"
            ],
            "lineageTag": "c4e03c86-c6cb-4c0c-8467-adf941d39c3e"
          },
          {
            "name": "90-day Rolling Profit",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-ZA\"}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Profit],",
              "    DATESINPERIOD(",
              "        'Calendar Lookup'[Date],",
              "        MAX (",
              "            'Calendar Lookup'[Date]",
              "        ),",
              "        -90,",
              "        DAY",
              "    )    ",
              ")"
            ],
            "formatString": "\"R\"#,0.###############;-\"R\"#,0.###############;\"R\"#,0.###############",
            "lineageTag": "c0892afc-3f0c-441b-bcca-38ae2f18fba0"
          },
          {
            "name": "Average Revenue Per Customer",
            "expression": [
              "",
              "DIVIDE(",
              "    [Total Revenue],",
              "    [Total Customers]",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "7448b9f0-1793-47fa-9c1d-557056e4fb2e"
          },
          {
            "name": "Profit Target",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-ZA\"}"
              }
            ],
            "expression": [
              "",
              "[90-day Rolling Profit] * 1.1",
              ""
            ],
            "formatString": "\"R\"#,0.###############;-\"R\"#,0.###############;\"R\"#,0.###############",
            "lineageTag": "2c6e86bc-8687-469f-a76e-bf6664781beb"
          },
          {
            "name": "Order Target Gap",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Total Orders] -[Order Target]",
            "lineageTag": "72820bda-5541-490e-b03b-ff574dfb0c0e"
          },
          {
            "name": "Revenue Target Gap",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-ZA\"}"
              }
            ],
            "expression": "[Total Revenue]- [Revenue Target]",
            "formatString": "\"R\"#,0.###############;-\"R\"#,0.###############;\"R\"#,0.###############",
            "lineageTag": "c91693bd-7992-40ee-8a08-cc27fb1186fa"
          },
          {
            "name": "Adjusted Price",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-ZA\"}"
              }
            ],
            "expression": "[Average Retails Price] * (1+'Price Adjustment (%)'[Price Adjustment (%) Value])",
            "formatString": "\"R\"#,0.###############;-\"R\"#,0.###############;\"R\"#,0.###############",
            "lineageTag": "f0d47857-064b-48f9-881f-28c8e9e9f3af"
          },
          {
            "name": "Adjusted Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-ZA\"}"
              }
            ],
            "expression": [
              "",
              "SUMX(",
              "    'Sales Data',",
              "    'Sales Data'[OrderQuantity]*",
              "    [Adjusted Price]",
              "    )"
            ],
            "formatString": "\"R\"#,0.###############;-\"R\"#,0.###############;\"R\"#,0.###############",
            "lineageTag": "ef7287a4-6cb9-4188-9a7b-18b4164ac796"
          },
          {
            "name": "Adjusted Profit",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-ZA\"}"
              }
            ],
            "expression": [
              "",
              "[Adjusted Revenue] - [Total Cost]"
            ],
            "formatString": "\"R\"#,0.###############;-\"R\"#,0.###############;\"R\"#,0.###############",
            "lineageTag": "dd4e2914-adf9-47eb-84a0-ac6b86c8586f"
          }
        ],
        "partitions": [
          {
            "name": "Measure Table",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Sales Data",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "OrderDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "21e352e8-c58c-42ea-a9b8-05e8be2c7769",
            "sourceColumn": "OrderDate",
            "summarizeBy": "none"
          },
          {
            "name": "StockDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "19d1635e-dedf-4670-9030-9a2db1715705",
            "sourceColumn": "StockDate",
            "summarizeBy": "none"
          },
          {
            "name": "OrderNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "a0498dd5-4d61-437d-b643-b6b9f6e5dfe8",
            "sourceColumn": "OrderNumber",
            "summarizeBy": "none"
          },
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ae5f2d0e-30f3-4e2f-ad7b-c33206312945",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0089ab6c-a21f-4f8c-aa51-bc1df12f0379",
            "sourceColumn": "CustomerKey",
            "summarizeBy": "none"
          },
          {
            "name": "TerritoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e00c6845-cb3f-4c79-9ce4-61fb486d20ec",
            "sourceColumn": "TerritoryKey",
            "summarizeBy": "none"
          },
          {
            "name": "OrderLineItem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "16361ed3-2692-4508-b86f-ff8e54bcd868",
            "sourceColumn": "OrderLineItem",
            "summarizeBy": "sum"
          },
          {
            "name": "OrderQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "11047040-eff8-4c9e-a61f-815968641caa",
            "sourceColumn": "OrderQuantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              " SUM(",
              "    'Sales Data'[OrderQuantity]",
              " )"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "ef69cdc1-263b-4b08-83d6-a7438d5390cb",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Quatity Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF(",
              "'Sales Data'[OrderQuantity]>1,",
              "\"Multiple Item\",",
              "\"Single Item\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "3cc32a72-a81f-432b-ae0f-133f2b1a3098",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Retail Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "decimal",
            "expression": [
              "",
              "RELATED(",
              "    'Product Lookup'[ProductPrice]",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "isDataTypeInferred": true,
            "lineageTag": "f444568d-3af1-4904-9e29-848db6e763dc",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "decimal",
            "expression": [
              "",
              "'Sales Data'[Retail Price] * 'Sales Data'[OrderQuantity]",
              ""
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "isDataTypeInferred": true,
            "lineageTag": "61f8bc82-6695-4cbf-a093-d03a0d715971",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "e220163d-eae0-49b9-90d5-fd20911e086f",
        "partitions": [
          {
            "name": "Sales Data",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Folder.Files(\"C:\\Users\\Rivashan Govender\\Downloads\\AdventureWorks+Raw+Data\\AdventureWorks Raw Data\\Sales Data\"),",
                "    #\"Filtered Hidden Files1\" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),",
                "    #\"Invoke Custom Function1\" = Table.AddColumn(#\"Filtered Hidden Files1\", \"Transform File (2)\", each #\"Transform File (2)\"([Content])),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Invoke Custom Function1\", {\"Name\", \"Source.Name\"}),",
                "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Renamed Columns1\", {\"Source.Name\", \"Transform File (2)\"}),",
                "    #\"Expanded Table Column1\" = Table.ExpandTableColumn(#\"Removed Other Columns1\", \"Transform File (2)\", Table.ColumnNames(#\"Transform File (2)\"(#\"Sample File (2)\"))),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Table Column1\",{{\"Source.Name\", type text}, {\"OrderDate\", type date}, {\"StockDate\", type date}, {\"OrderNumber\", type text}, {\"ProductKey\", Int64.Type}, {\"CustomerKey\", Int64.Type}, {\"TerritoryKey\", Int64.Type}, {\"OrderLineItem\", Int64.Type}, {\"OrderQuantity\", Int64.Type}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Source.Name\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Product Lookup",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bbe73043-cf8a-4b12-849b-24e6913dc6cf",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "ProductSubcategoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4934ab2f-a7e8-48d1-868c-95f802f1b731",
            "sourceColumn": "ProductSubcategoryKey",
            "summarizeBy": "none"
          },
          {
            "name": "ProductSKU",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "684a1516-4944-4ec8-9b49-05971d6bbd78",
            "sourceColumn": "ProductSKU",
            "summarizeBy": "none"
          },
          {
            "name": "ProductName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5a63b425-0dd7-473a-aeea-72ca61b71009",
            "sourceColumn": "ProductName",
            "summarizeBy": "none"
          },
          {
            "name": "ModelName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "07f77df2-f2c6-4263-bed3-32681605391d",
            "sourceColumn": "ModelName",
            "summarizeBy": "none"
          },
          {
            "name": "ProductDescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9eef69f6-7731-4379-a017-78e2d23b61c9",
            "sourceColumn": "ProductDescription",
            "summarizeBy": "none"
          },
          {
            "name": "ProductColor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "049e3e35-5dc1-4a68-acbf-23746b79b602",
            "sourceColumn": "ProductColor",
            "summarizeBy": "none"
          },
          {
            "name": "ProductSize",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9c450264-ebab-4976-a12f-cb2552c2f169",
            "sourceColumn": "ProductSize",
            "summarizeBy": "none"
          },
          {
            "name": "ProductStyle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "21bb3e19-49dd-466f-8cd8-106cde10113a",
            "sourceColumn": "ProductStyle",
            "summarizeBy": "none"
          },
          {
            "name": "ProductCost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-ZA\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\"R\"#,0.###############;-\"R\"#,0.###############;\"R\"#,0.###############",
            "lineageTag": "ec07e6bd-f84c-4916-adc5-a9fd493ba769",
            "sourceColumn": "ProductCost",
            "summarizeBy": "sum"
          },
          {
            "name": "ProductPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-ZA\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\"R\"#,0.###############;-\"R\"#,0.###############;\"R\"#,0.###############",
            "lineageTag": "ff603f34-a3eb-4628-b20d-acefc383ea15",
            "sourceColumn": "ProductPrice",
            "summarizeBy": "sum"
          },
          {
            "name": "Price Point",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    'Product Lookup'[ProductPrice] > 500,\"High\",",
              "    'Product Lookup'[ProductPrice] > 100,\"Mid Range\",",
              "    \"Low\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "b50937be-f4ff-47a1-bb06-8038d0abc431",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "SKU Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "LEFT(",
              "    'Product Lookup'[ProductSKU],",
              "    SEARCH(",
              "        \"-\",",
              "        'Product Lookup'[ProductSKU]",
              "    )",
              "    -1",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "0df60386-06c8-4c98-80d9-3558209c7afe",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "743aa4e2-dbbd-4116-9fd8-ead109576bb8",
        "partitions": [
          {
            "name": "Product Lookup",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\Rivashan Govender\\Downloads\\AdventureWorks+Raw+Data\\AdventureWorks Raw Data\\AdventureWorks Product Lookup.csv\"),[Delimiter=\",\", Columns=11, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ProductKey\", Int64.Type}, {\"ProductSubcategoryKey\", Int64.Type}, {\"ProductSKU\", type text}, {\"ProductName\", type text}, {\"ModelName\", type text}, {\"ProductDescription\", type text}, {\"ProductColor\", type text}, {\"ProductSize\", type text}, {\"ProductStyle\", type text}, {\"ProductCost\", Currency.Type}, {\"ProductPrice\", Currency.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Price Adjustment (%)",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "04a5df173faf4a448a01dae157ea32a8"
          }
        ],
        "columns": [
          {
            "name": "Price Adjustment (%)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "version": 0
                }
              }
            ],
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "aec3f430-0f56-4cb8-ad79-52e7f05cbb5c",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "f5ded240-b11d-49bc-ae2d-455ea60d1d84",
        "measures": [
          {
            "name": "Price Adjustment (%) Value",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SELECTEDVALUE('Price Adjustment (%)'[Price Adjustment (%)], 0)",
            "lineageTag": "a090a984-4120-49b1-ae2b-6ad895eeb51d"
          }
        ],
        "partitions": [
          {
            "name": "Price Adjustment (%)",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(-1, 1, 0.1)",
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}