version: '3.8'

services:
      
  main_app:
    build:
      context: ./main_app
      dockerfile: DockerFile
    ports:
      - "8000:8000"
    volumes:
      - ./main_app:/app 
    depends_on:
      - user_service
      - product_service
    environment:
      - DATABASE_URL=sqlite:///app/data/Recipe.db # Ensure consistency
    networks:
      - app-network

  user_service:
    build:
      context: ./user_service
      dockerfile: DockerFile
    ports:
      - "8002:8000"
    volumes:
      - ./user_service:/app
      - ./main_app/Frontend/templates:/app/templates
      - ./main_app/static/images:/app/static
      - ./data:/app/data 
    environment:
      - DATABASE_URL=sqlite:///app/data/Recipe.db # Ensure consistency
    networks:
      - app-network

  product_service:
    build:
      context: ./product_service
      dockerfile: DockerFile
    ports:
      - "8001:8000"
    volumes:
      - ./product_service:/app
      - ./main_app/Frontend/templates:/app/templates
      - ./main_app/static/images:/app/static
      - ./data:/app/data # Using named volume for product db
    environment:
      - DATABASE_URL=sqlite:///app/data/Recipe.db # Ensure consistency
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    volumes:
      - ./main_app/Frontend/templates:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - main_app
      - user_service
      - product_service
    networks:
      - app-network

volumes:
  data:
    driver: local

networks:
  app-network:
    driver: bridge