table CreditCard

	column CreditID
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: CreditID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	partition CreditCard = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Rivashan Govender\Downloads\YouTube -Banking Report\CreditCard.xlsx"), null, true),
				    Table1_Table = Source{[Item="Table1",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Table1_Table,{{"CreditID", Int64.Type}, {"Category", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

