table Geography

	column GeographyID
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: GeographyID

		annotation SummarizationSetBy = Automatic

	column GeographyLocation
		dataType: string
		summarizeBy: none
		sourceColumn: GeographyLocation

		annotation SummarizationSetBy = Automatic

	partition Geography = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Rivashan Govender\Downloads\YouTube -Banking Report\Geography.xlsx"), null, true),
				    Table1_Table = Source{[Item="Table1",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Table1_Table,{{"GeographyID", Int64.Type}, {"GeographyLocation", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

