table 'Customer Lookup'
	lineageTag: 2d091376-2894-40e2-991f-3394b2512e98

	column customer_id
		dataType: int64
		formatString: 0
		lineageTag: a8cf53a8-9cd1-47ef-b6ef-161b7ec97f71
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column home_store
		dataType: int64
		formatString: 0
		lineageTag: 7150e2ad-11d5-47ff-957d-551d1009f4a1
		summarizeBy: sum
		sourceColumn: home_store

		annotation SummarizationSetBy = Automatic

	column customer_first-name
		dataType: string
		lineageTag: 31e4cdc8-414e-4cd2-8c6f-b3ae292d8fc0
		summarizeBy: none
		sourceColumn: customer_first-name

		annotation SummarizationSetBy = Automatic

	column customer_email
		dataType: string
		lineageTag: f31335b2-3381-41f3-a606-049daad21eac
		summarizeBy: none
		sourceColumn: customer_email

		annotation SummarizationSetBy = Automatic

	column customer_since
		dataType: dateTime
		formatString: Long Date
		lineageTag: 148aa980-f1bf-403b-9654-1303e1488556
		summarizeBy: none
		sourceColumn: customer_since

		variation Variation
			isDefault
			relationship: a4c1edaa-4843-4360-aa22-b0301be38216
			defaultHierarchy: LocalDateTable_135e50b1-bccc-45e0-aa06-78b5092657af.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column loyalty_card_number
		dataType: string
		lineageTag: 691c46bf-4b65-4288-88c4-14cafc6768e5
		summarizeBy: none
		sourceColumn: loyalty_card_number

		annotation SummarizationSetBy = Automatic

	column birthdate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 54b9e118-f739-4ea3-b252-42c1aa0ac2c0
		summarizeBy: none
		sourceColumn: birthdate

		variation Variation
			isDefault
			relationship: b2686902-935d-47b1-aa6c-5d719431a9f5
			defaultHierarchy: LocalDateTable_38a5449e-f824-4b56-9b99-642debd79e41.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column gender
		dataType: string
		lineageTag: ab703f44-26d1-45d8-b68a-2d0306c073a8
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column birth_year
		dataType: int64
		formatString: 0
		lineageTag: d0549e3e-0e06-4006-9f95-2a48fab6c86c
		summarizeBy: sum
		sourceColumn: birth_year

		annotation SummarizationSetBy = Automatic

	column 'Current Age' =
			
			FLOOR(
			    DATEDIFF(
			        'Customer Lookup' [birthdate],
			        TODAY(),
			        DAY
			    ) / 365.25,
			    1
			)
		dataType: int64
		formatString: 0
		lineageTag: 92fd0a09-7343-4dc1-a466-6333b12a38b2
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column 'Customer Sales (High/Low)' = ```
			
			VAR TotalSales = 
			SUMX(
			    'Sales by Store',
			    'Sales by Store'[quantity_sold] * 'Sales by Store'[unit_price]
			)
			VAR AllCustomers = 
			COUNTROWS('Customer Lookup')
			VAR AvgSales =
			DIVIDE(TotalSales,AllCustomers)
			VAR CustomerSales =
			SUMX(
			    RELATEDTABLE(
			        'Sales by Store'
			    ),
			    'Sales by Store'[quantity_sold] * 'Sales by Store'[unit_price]
			)
			VAR HighLow =
			IF(
			    CustomerSales > AvgSales,
			    "High",
			    "Low"
			)
			RETURN
			HighLow
			```
		dataType: string
		lineageTag: e50c05ef-610d-414d-b8ae-df6bf8e8f910
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	partition 'Customer Lookup' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Rivashan Govender\Downloads\Udemy Resources\Microsoft Power BI Desktop Advanced DAX for Data Analysis\Advanced+DAX+Data+Files\Advanced DAX Data Files\Customer Lookup.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"customer_id", Int64.Type}, {"home_store", Int64.Type}, {"customer_first-name", type text}, {"customer_email", type text}, {"customer_since", type date}, {"loyalty_card_number", type text}, {"birthdate", type date}, {"gender", type text}, {"birth_year", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

