table 'Employee Lookup'
	lineageTag: bb05806b-f2e0-4732-af03-f1854e3ec9a1

	column staff_id
		dataType: int64
		formatString: 0
		lineageTag: e5b29e28-966b-4445-9e45-26baa6d66726
		summarizeBy: none
		sourceColumn: staff_id

		annotation SummarizationSetBy = Automatic

	column first_name
		dataType: string
		lineageTag: d2da3a1f-2620-4c32-9475-1ed1b85b78e1
		summarizeBy: none
		sourceColumn: first_name

		annotation SummarizationSetBy = Automatic

	column last_name
		dataType: string
		lineageTag: 76a03cbc-baf8-4cba-b443-5080a4c46452
		summarizeBy: none
		sourceColumn: last_name

		annotation SummarizationSetBy = Automatic

	column position
		dataType: string
		lineageTag: b83a445d-c2c5-4750-89dd-9ae3a46c6c3e
		summarizeBy: none
		sourceColumn: position

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 74c1176e-3005-40a4-a15f-ce886a4adcb2
		summarizeBy: none
		sourceColumn: start_date

		variation Variation
			isDefault
			relationship: 984c785b-86e6-4ee7-9db7-aaf5ecdd150e
			defaultHierarchy: LocalDateTable_24d2ea5b-9f80-41a8-86da-3be25896dd10.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column location
		dataType: string
		lineageTag: 14a95dd2-44f7-4619-8fe6-3c7cdf5190e9
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	partition 'Employee Lookup' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Rivashan Govender\Downloads\Udemy Resources\Microsoft Power BI Desktop Advanced DAX for Data Analysis\Advanced+DAX+Data+Files\Advanced DAX Data Files\Employee Lookup.csv"),[Delimiter=",", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"staff_id", Int64.Type}, {"first_name", type text}, {"last_name", type text}, {"position", type text}, {"start_date", type date}, {"location", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

