table 'Food Inventory'
	lineageTag: 8aeaca0a-8817-43a7-a427-471ba497d6c3

	column store_id
		dataType: int64
		formatString: 0
		lineageTag: 1aa27209-c233-4754-9d9c-cef8ace2ebdd
		summarizeBy: none
		sourceColumn: store_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column baked_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3b86a0f4-c998-45da-a31a-e35f5476be76
		summarizeBy: none
		sourceColumn: baked_date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column transaction_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9a681163-9717-4fa9-956d-5eab98a6a28b
		summarizeBy: none
		sourceColumn: transaction_date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column product_id
		dataType: int64
		formatString: 0
		lineageTag: 4d914b5b-0422-4929-a28f-9678cb3d249c
		summarizeBy: none
		sourceColumn: product_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column quantity_start_of_day
		dataType: int64
		formatString: 0
		lineageTag: 3224d94e-7755-40fa-b852-bdd7e1e04ff5
		summarizeBy: sum
		sourceColumn: quantity_start_of_day

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column quantity_sold
		dataType: int64
		formatString: 0
		lineageTag: 92634caf-efda-43a7-8c2c-2ef4dba4b2f5
		summarizeBy: sum
		sourceColumn: quantity_sold

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Quantity Sold (CALCULATE)' =
			
			CALCULATE(
			    SUM(
			    'Food Inventory'[quantity_sold]
			    )
			)
		dataType: int64
		formatString: 0
		lineageTag: 2b9bcdc9-621f-4ddd-ba51-de6898b4324f
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	partition 'Food Inventory' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Rivashan Govender\Downloads\Udemy Resources\Microsoft Power BI Desktop Advanced DAX for Data Analysis\Advanced+DAX+Data+Files\Advanced DAX Data Files\Food Inventory.csv"),[Delimiter=",", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"store_id", Int64.Type}, {"baked_date", type date}, {"transaction_date", type date}, {"product_id", Int64.Type}, {"quantity_start_of_day", Int64.Type}, {"quantity_sold", Int64.Type}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

