USE AutomatedDatabase
go

BEGIN

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'UserInfo')
CREATE TABLE UserInfo
(	
	UserID INT NOT NULL,
	Name VARCHAR(50) NOT NULL
)
END 

BEGIN
INSERT INTO UserInfo (UserId, Name)VALUES (1, 'Elon');
END
