USE temp_db
go

BEGIN

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Table123')
CREATE TABLE Table123
(	
	UserID INT NOT NULL,
	Name VARCHAR(50) NOT NULL
)
END 

BEGIN
INSERT INTO Table123 (UserId, Name)VALUES (2, 'Test name');
END
