name: Deployment

on:
  push:
    branches: [ main ]

env:
  PROFILE: Files
  ENVIRONMENT: PROD

jobs:
  Deployment:
    runs-on: windows-latest
    environment: PROD

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: 'true'

      - name: List files in C:\PowerBI\DevOps
        run: dir C:/Program Files/Git/Rivashan_Govender/PowerBI/DevOps
        shell: cmd

      - name: pbi-tools deploy
        run: |
          pbi-tools.core deploy . files PROD
        env:
          PBI_CLIENT_SECRET: ${{ secrets.PBI_CLIENT_SECRET }}
        shell: cmd
