name: Deployment

# Controls when the workflow will run
on:
  push:
    branches: [ main ]

env:
  PROFILE: files
  ENVIRONMENT: PROD

jobs:
  Deployment:
    runs-on: ubuntu-latest
    environment: PROD
    container:
      image: ghcr.io/pbi-tools/pbi-tools-core:latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          lfs: 'true'
          
      - name: Change directory to PowerBI/DevOps
        run: cd PowerBI/DevOps

      - name: pbi-tools deploy
        run: /app/pbi-tools/pbi-tools.core deploy . files PROD
        env:
          PBI_CLIENT_SECRET: ${{ secrets.PBI_CLIENT_SECRET }}
