name: Deploy SSIS Package

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SQL Server Integration Services
      run: |
        sudo apt-get update
        sudo apt-get install -y mssql-server-integration-services

    - name: Deploy SSIS Package
      run: |
        sudo -u $(SQL_USERNAME) /opt/mssql/bin/dtutil -s $(SQLDB_SERVER) -f /DatabaseAdministration/SSIS/GraduateMultiFile/Package.dtsx -i /DatabaseAdministration/SSIS/ispac/GraduateMultiFile.ispac -k

      env:
        SQL_SERVER_NAME: ${{ secrets.SQLDB_SERVER }}
        SQL_USERNAME: ${{ secrets.SQLDB_USERNAME }}
        SQL_PASSWORD: ${{ secrets.SQLDB_PASSWORD }}
